os: 
  - linux

dist: bionic

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "2.7"
    - "nightly"

matrix:
    allow_failures:
        - python: "2.7"
        - python: "nightly"

branches:
  only:
    - master
    - stable

install:
    - pip install pipenv --upgrade-strategy=only-if-needed
    - pipenv install --dev --ignore-pipfile

script: ls -la &&
        exam-terminal --help

# TODO: 
#   Figure out windows and osx tests jobs
#   Code linting and formatting check (diff jobs?)