os: 
  - linux

dist: bionic

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

matrix:
    allow_failures:
        - python: 
            - "2.7"
            - "nightly"

branches:
  only:
    - master
    - stable

install:
    - pip install pipenv --upgrade-strategy=only-if-needed
    - pipenv install --dev --ignore-pipfile

script: ls -la &&
        exam-terminal --help

# after_script:
#     - bash <(curl -s https://codecov.io/bash)

# Travis CI Life cycle
#   https://docs.travis-ci.com/user/job-lifecycle/

# TODO: Figure out windows and osx tests jobs