os:
  - linux

dist: bionic

language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

matrix:
  allow_failures:
    - python: "nightly"

branches:
  only:
    - master
    - dev
    - stable

# FIXME: Omit travis build on changes in .md files
# before_install:
#   - bash scripts/preflight.sh $TRAVIS_COMMIT $TRAVIS_BRANCH || travis_terminate 1;

install:
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade-strategy=only-if-needed pipenv setuptools wheel twine build
  - pipenv install --deploy --dev

script:
    - pipenv graph
    - pwd 
    - pipenv run pip list
    - pipenv run exam-terminal --help

deploy:
  - provider: pypi
    username: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    edge: true  # Opt in to travis CI dpl v2
    distributions: "sdist bdist_wheel"
    skip_existing: true  # Prevent competing deploy builds
    on:
      branch: master

  - provider: pypi
    server: https://test.pypi.org/legacy/  # Comment out to deploy to PYPI
    username: $TEST_PYPI_USERNAME
    password: $TEST_PYPI_PASSWORD
    edge: true  # Opt in to travis CI dpl v2
    distributions: "sdist bdist_wheel"
    skip_existing: true  # Prevent competing deploy builds
    on:
      branch: dev

