os:
  - linux

dist: bionic

language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

matrix:
  allow_failures:
    - python: "nightly"

branches:
  only:
    - master
    - stable

# before_install:
#   - bash scripts/preflight.sh $TRAVIS_COMMIT $TRAVIS_BRANCH || travis_terminate 1;

install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev --ignore-pipfile

script: ls -la &&
        exam-terminal --help

deploy:
  provider: pypi
  # server: https://test.pypi.org/legacy/  # Comment out to deploy to PYPI
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  edge: true  # Opt in to travis CI dpl v2
  distributions: "sdist bdist_wheel"
  skip_existing: true  # Prevent competing deploy builds


# TODO:
#   Figure out windows and osx tests jobs
#   Code linting and formatting check (diff jobs?)
#   Automatic update PYPI form master branch change
#   Automatic update TestPYPI on development branch
